version: '3'

services:
  financial-app:
    build: .
    image: felipearaujo/fiap-app:latest
    ports:
      - 4000:4000
    depends_on:
      - db  

  db:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: fiap
