version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
  
  db:
    image: bitnami/mongodb:5.0.17
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db    
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: fiap

volumes:
  mongodb_data:
    driver: local

networks:
  my-network:
    external: true