version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
  
  db:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: fiap

volumes:
  mongodb_data:
    driver: local

networks:
  my-network:
    external: true